payment-config.supportedAccounts: BARCELONA,TENERIFE,CRETE,LONDON,PARIS

management.endpoints.web.base-path: "/"
management.endpoints.web.exposure.include: "*"
management.health.defaults.enabled: true


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: false
  security:
    enabled: false

harness:
  se: ${HARNESS_SE:nik}
  build: ${HARNESS_BUILD:1}
  api:
    key: ${HARNESS_FF_KEY:1260ecd9-0af2-43d0-98f6-06570bb13a00}